# Axle Configuration File
# This file defines package managers, dependencies, and settings for Axle.
# List of package managers to use
# Each manager has a `commands` (CLI tool used) and a list of `packages`.
package_managers:

# Examples
# pip:
#   packages:
#     requests: {version: "latest", enabled: true}
#     numpy: {version: "latest", enabled: true}
#   go:
#     commands:
#       add: "get"
#       remove: "" # Go doesn't really have an uninstall command, I guess.
#       clean: "mod tidy"
#     packages:
#       github.com/Nykenik24/axle: {version: "latest", enabled: true}
# Global settings for dependency management
# Status: TODO
# global:
#   parallel: {version: "latest", enabled: true} # Run package installations in parallel
#   cache: {version: "latest", enabled: true} # Enable local caching for offline installs
#   lockfile: {version: "latest", enabled: true} # Generate an axle.lock.yaml file
# Custom commands for non-standard package managers
# This allows defining additional dependency managers manually.
# Status: TODO
# custom:
#   mypkg:
#     commands:
#       add: "mypkg-add"
#       remove: "mypkg-delete"
#       update: "mypkg-refresh"
#     packages:
#       somepackage: {version: "latest", enabled: true}
# Dependency graph settings. 
# Status: TODO
# graph:
#   format: "json" # Options: json, yaml, dot
#   output_file: "axle-dependencies.json"
